<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tgm_copyright"
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Picture Copyrights and Image Sitemap.',
  'description' => 'This extension will add a copyright field on every image palette and can show it below each image. All pictures with a copyright can be listed with a plugin. An Image Sitemap XML for Google of ALL used images can be generated by this extension.',
  'category' => 'plugin',
  'author' => 'Paul Beck',
  'author_email' => 'hi@toll-paul.de',
  'state' => 'beta',
  'uploadfolder' => false,
  'clearCacheOnLoad' => 1,
  'version' => '3.0.6',
  'constraints' => 
  array (
    'depends' => 
    array (
      'typo3' => '11.5.1-11.5.99',
      'filemetadata' => '11.5.1-11.5.99',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  'clearcacheonload' => true,
  'author_company' => NULL,
);

